function tests = test_circadian_fig5b_reconstruction
%TEST_CIRCADIAN_FIG5B_RECONSTRUCTION Regression coverage for circadian per-curve caches.

tests = functiontests(localfunctions);
end

function setupOnce(testCase)
testDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(testDir);
addpath(rootDir, '-begin');
addpath(fullfile(rootDir, 'Circadian'), '-begin');
testCase.TestData.rootDir = rootDir;
end

function setup(testCase)
global RUN_MODULATION_TASK_LOG
RUN_MODULATION_TASK_LOG = {};

stubDir = tempname;
mkdir(stubDir);
write_run_circadian_fmam_task_stub(stubDir);

circadian.ensure_paths();
addpath(stubDir, '-begin');
clear run_circadian_fmam_task

testCase.TestData.stubDir = stubDir;
testCase.TestData.cleanupPath = onCleanup(@() cleanup_stub_dir(stubDir));
end

function teardown(~)
global RUN_MODULATION_TASK_LOG
RUN_MODULATION_TASK_LOG = {};
close all force
end

function testBuildFig5bProducesOneCurveCachePerIsoLineAndIndependentMarks(testCase)
global RUN_MODULATION_TASK_LOG

cfg = make_test_cfg();
curveData = build_fig5b_data(cfg);
curveLogs = RUN_MODULATION_TASK_LOG;

verifyEqual(testCase, numel(curveData.curves), 1);
verifyEqual(testCase, numel(curveData.curveFiles), 1);
verifyTrue(testCase, isfile(curveData.curveFiles{1}));

curve = curveData.curves{1};
branchNames = {'lowerLeft', 'lowerRight', 'upperLeft', 'upperRight'};
for i = 1:numel(branchNames)
    branch = curve.branches.(branchNames{i});
    verifyTrue(testCase, all(isfield(branch, ...
        {'paramMatrix', 'Kd', 'AT', 'period', 'obsAmplitude', 'obsMax', ...
         'directConditionEstimate', 'stopReason'})));
    verifyGreaterThanOrEqual(testCase, numel(branch.Kd), 1);
    verifyEqual(testCase, issorted(branch.Kd), true);
end

verifyEqual(testCase, sort(unique(curve.allPoints.branchId)), sort(branchNames(:)));
verifyEqual(testCase, size(curve.allPoints.paramMatrix, 1), 8);

verifyEqual(testCase, numel(curveLogs), 6);
verifyEqual(testCase, numel(filter_logs(curveLogs, {'period', 'AT'})), 2);
verifyEqual(testCase, numel(filter_logs(curveLogs, {'period', 'Kd'})), 4);

RUN_MODULATION_TASK_LOG = {};
markData = build_fig5b_marks(cfg);
markLogs = RUN_MODULATION_TASK_LOG;

verifyEqual(testCase, numel(markData.markFiles), numel(cfg.fig5b.markAmplitudes));
verifyTrue(testCase, all(cellfun(@isfile, markData.markFiles)));
verifyEqual(testCase, numel(markLogs), numel(cfg.fig5b.markAmplitudes));
for i = 1:numel(markLogs)
    verifyEqual(testCase, markLogs{i}.startParams, cfg.fig5b.markSeeds(i, :), 'AbsTol', 1e-12);
end
end

function testBuildFig5cUsesMarkCachesWithoutCurveCaches(testCase)
global RUN_MODULATION_TASK_LOG

cfg = make_test_cfg();
markData = build_fig5b_marks(cfg);
verifyTrue(testCase, all(cellfun(@isfile, markData.markFiles)));

RUN_MODULATION_TASK_LOG = {};
data = build_fig5c_data(cfg);

verifyEqual(testCase, numel(RUN_MODULATION_TASK_LOG), 0);
verifyEqual(testCase, numel(data.series), numel(cfg.fig5b.markAmplitudes));
verifyEqual(testCase, data.markAmplitudes, cfg.fig5b.markAmplitudes, 'AbsTol', 1e-12);
end

function testReproduceAllFig5BuildsPerCurveAndPerMarkCachesFromEmptyRoot(testCase)
cfg = make_test_cfg();
cfg.fig5d.maxima = [0.12, 0.10];
cfg.fig5d.ATseed = [0.045, 0.03];
cfg.fig5d.Kdseed = [5e-5, 5e-5];
cfg.fig5d.markPeriods = [23.5, 24];
cfg.fig5d.markSeeds = [8.5e-5, 0.045; 6.5e-5, 0.035];
cfg.fig5d.sde.representativeSeeds = [1, 2];
cfg.figS2a.amplitudes = [0.02, 0.03];

result = reproduce_all_fig5(cfg);

verifyTrue(testCase, isfile(circadian.curve_cache_file(cfg, 'fig5b', 'period', cfg.fig5b.periods(1))));
verifyTrue(testCase, isfile(circadian.curve_cache_file(cfg, 'fig5d', 'maximum', cfg.fig5d.maxima(1))));
verifyTrue(testCase, isfile(circadian.curve_cache_file(cfg, 'figS2a', 'amplitude', cfg.figS2a.amplitudes(1))));
verifyTrue(testCase, isfile(circadian.mark_cache_file(cfg, 'fig5b', 'amplitude_01')));
verifyTrue(testCase, isfile(circadian.mark_cache_file(cfg, 'fig5d', 'period_01')));

verifyTrue(testCase, isgraphics(result.fig5b.figure));
verifyTrue(testCase, isgraphics(result.fig5c.figure));
verifyTrue(testCase, isgraphics(result.fig5d.figure));
verifyTrue(testCase, isgraphics(result.figS2a.figure));
end

function entries = filter_logs(logEntries, goalOrder)
mask = cellfun(@(entry) isequal(entry.goalOrder, goalOrder), logEntries);
entries = logEntries(mask);
end

function cfg = make_test_cfg()
cfg = default_config();
cfg.fig5b.periods = 24;
cfg.fig5b.seedKd = 5e-5;
cfg.fig5b.lowerSeedAt = 0.025;
cfg.fig5b.upperSeedAt = 0.050;
cfg.fig5b.markPeriod = 24;
cfg.fig5b.markAmplitudes = [0.015, 0.025, 0.035];
cfg.fig5b.markSeeds = [4e-5, 0.018; 7e-5, 0.028; 1.1e-4, 0.038];
cfg.fig5b.KdAxis = [1e-5, 1.4e-4];
cfg.fig5b.ATAxis = [0.01, 0.09];
cfg.fig5b.maxParamJump = [1, 1];
cfg.fig5b.maxAmplitudeJump = 1;

cfg.fig5d.maxima = [0.12];
cfg.fig5d.ATseed = 0.045;
cfg.fig5d.markMaximum = 0.12;
cfg.fig5d.markPeriods = [23.5, 24, 24.5];
cfg.fig5d.markSeeds = [9e-5, 0.05; 8e-5, 0.045; 7e-5, 0.04];
cfg.fig5d.KdRange = [1e-5, 1.4e-4];
cfg.fig5d.KdAxis = [1e-5, 1.4e-4];
cfg.fig5d.ATAxis = [0.01, 0.09];
cfg.fig5d.maxParamJump = [1, 1];
cfg.fig5d.maxPeriodJump = 10;
cfg.fig5d.sde.representativeSeeds = [1, 2, 3];
cfg.fig5d.sde.psdSeeds = 101:103;
cfg.fig5d.sde.distributionSeeds = 101:103;
cfg.fig5d.sde.nReplicates = 3;
cfg.fig5d.sde.representativeWarmupT = 2;
cfg.fig5d.sde.representativeMeasureT = 4;
cfg.fig5d.sde.psdWarmupT = 2;
cfg.fig5d.sde.psdMeasureT = 4;
cfg.fig5d.sde.distributionWarmupT = 2;
cfg.fig5d.sde.distributionMeasureT = 4;
cfg.fig5d.sde.dt = 0.1;
cfg.fig5d.sde.plotSigma = 0.4;
cfg.fig5d.sde.sigma = 0.4;
cfg.fig5d.sde.parallelWorkers = 1;
cfg.fig5d.sde.psdBandPercentiles = [10, 90];

cfg.figS2a.amplitudes = [0.02];
cfg.figS2a.centerPeriod = 24;
cfg.figS2a.KdRange = [1e-5, 1.4e-4];
cfg.figS2a.KdAxis = [1e-5, 1.4e-4];
cfg.figS2a.ATAxis = [0.01, 0.09];
cfg.figS2a.maxParamJump = [1, 1];
cfg.figS2a.maxPeriodJump = 10;

cfg.fmam.dlambdaCap = 0.25;

tempRoot = tempname;
mkdir(tempRoot);
cfg.io.cacheDir = fullfile(tempRoot, 'cache');
cfg.io.figureDir = fullfile(tempRoot, 'figure');
end

function cleanup_stub_dir(stubDir)
if isfolder(stubDir)
    rmpath(stubDir);
    clear run_circadian_fmam_task
    try
        rmdir(stubDir, 's');
    catch
    end
end
end

function write_run_circadian_fmam_task_stub(stubDir)
stubPath = fullfile(stubDir, 'run_circadian_fmam_task.m');
fid = fopen(stubPath, 'w');
assert(fid >= 0, 'Failed to create run_circadian_fmam_task stub.');
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

lines = { ...
    'function result = run_circadian_fmam_task(cfg)', ...
    'global RUN_MODULATION_TASK_LOG', ...
    'if isempty(RUN_MODULATION_TASK_LOG), RUN_MODULATION_TASK_LOG = {}; end', ...
    'startParams = resolve_start_params(cfg);', ...
    'RUN_MODULATION_TASK_LOG{end + 1} = struct(''startParams'', startParams, ''goalOrder'', {cfg.goalOrder}, ''goals'', cfg.goals);', ...
    'goalOrder = cfg.goalOrder;', ...
    'if isequal(goalOrder, {''period'', ''AT''})', ...
    '    params = [startParams(1), cfg.goals.AT];', ...
    '    amplitude = max(cfg.goals.AT * 0.5, 0.005);', ...
    '    maximum = amplitude + 0.10;', ...
    '    result = make_result({''Kd'', ''AT''}, params, cfg.goals.period, amplitude, maximum, []);', ...
    'elseif isequal(goalOrder, {''period'', ''Kd''})', ...
    '    result = make_period_kd_branch(cfg);', ...
    'elseif isequal(goalOrder, {''period'', ''amplitude''})', ...
    '    params = startParams;', ...
    '    result = make_result({''Kd'', ''AT''}, params, cfg.goals.period, cfg.goals.amplitude, cfg.goals.amplitude + 0.10, []);', ...
    'elseif isequal(goalOrder, {''maximum'', ''AT''})', ...
    '    params = [startParams(1), cfg.goals.AT];', ...
    '    amplitude = max(0.5 * cfg.goals.maximum, 0.01);', ...
    '    result = make_result({''Kd'', ''AT''}, params, 24, amplitude, cfg.goals.maximum, []);', ...
    'elseif isequal(goalOrder, {''maximum'', ''Kd''})', ...
    '    result = make_maximum_kd_branch(cfg);', ...
    'elseif isequal(goalOrder, {''maximum'', ''period''})', ...
    '    params = startParams;', ...
    '    amplitude = max(0.5 * cfg.goals.maximum, 0.01);', ...
    '    result = make_result({''Kd'', ''AT''}, params, cfg.goals.period, amplitude, cfg.goals.maximum, []);', ...
    'elseif isequal(goalOrder, {''amplitude'', ''period''})', ...
    '    params = startParams;', ...
    '    result = make_result({''Kd'', ''AT''}, params, cfg.goals.period, cfg.goals.amplitude, cfg.goals.amplitude + 0.10, []);', ...
    'elseif isequal(goalOrder, {''amplitude'', ''Kd''})', ...
    '    result = make_amplitude_kd_branch(cfg);', ...
    'else', ...
    '    error(''test:UnexpectedGoalOrder'', ''Unexpected goalOrder in stub.'');', ...
    'end', ...
    'end', ...
    '', ...
    'function params = resolve_start_params(cfg)', ...
    'if isfield(cfg, ''startParams'') && ~isempty(cfg.startParams)', ...
    '    params = reshape(cfg.startParams, 1, []);', ...
    'elseif isfield(cfg, ''initialSolverView'') && isfield(cfg.initialSolverView, ''params'')', ...
    '    params = reshape(cfg.initialSolverView.params, 1, []);', ...
    'else', ...
    '    error(''test:MissingStartParams'', ''Missing start params in stub.'');', ...
    'end', ...
    'end', ...
    '', ...
    'function result = make_period_kd_branch(cfg)', ...
    'params = resolve_start_params(cfg);', ...
    'atSeed = params(2);', ...
    'targetKd = cfg.goals.Kd;', ...
    'isLower = atSeed < 0.04;', ...
    'isLeft = targetKd <= params(1);', ...
    'if isLower && isLeft', ...
    '    amplitudes = [0.018; 0.012]; atValues = [atSeed; atSeed - 0.003]; stopReason = ''lowerLeft'';', ...
    'elseif isLower', ...
    '    amplitudes = [0.022; 0.028]; atValues = [atSeed; atSeed + 0.003]; stopReason = ''lowerRight'';', ...
    'elseif isLeft', ...
    '    amplitudes = [0.038; 0.032]; atValues = [atSeed; atSeed - 0.003]; stopReason = ''upperLeft'';', ...
    'else', ...
    '    amplitudes = [0.042; 0.048]; atValues = [atSeed; atSeed + 0.003]; stopReason = ''upperRight'';', ...
    'end', ...
    'paramMatrix = [params(1), atValues(1); targetKd, atValues(2)];', ...
    'period = cfg.goals.period * ones(2, 1);', ...
    'result = make_result({''Kd'', ''AT''}, paramMatrix(end, :), period(end), amplitudes(end), amplitudes(end) + 0.10, make_path({''Kd'', ''AT''}, paramMatrix, period, amplitudes, amplitudes + 0.10, stopReason));', ...
    'end', ...
    '', ...
    'function result = make_maximum_kd_branch(cfg)', ...
    'params = resolve_start_params(cfg);', ...
    'targetKd = cfg.goals.Kd;', ...
    'atValues = [params(2); params(2) + 0.01 * sign(targetKd - params(1) + eps)];', ...
    'period = [cfg.goals.maximum * 100 + 12; cfg.goals.maximum * 100 + 13];', ...
    'amplitude = max(0.5 * cfg.goals.maximum, 0.01) * [1; 1.05];', ...
    'maximum = cfg.goals.maximum * [1; 1];', ...
    'stopReason = ''target_reached'';', ...
    'paramMatrix = [params(1), atValues(1); targetKd, atValues(2)];', ...
    'result = make_result({''Kd'', ''AT''}, paramMatrix(end, :), period(end), amplitude(end), maximum(end), make_path({''Kd'', ''AT''}, paramMatrix, period, amplitude, maximum, stopReason));', ...
    'end', ...
    '', ...
    'function result = make_amplitude_kd_branch(cfg)', ...
    'params = resolve_start_params(cfg);', ...
    'targetKd = cfg.goals.Kd;', ...
    'atValues = [params(2); params(2) + 0.008 * sign(targetKd - params(1) + eps)];', ...
    'basePeriod = 24;', ...
    'period = [basePeriod; basePeriod + 0.4];', ...
    'amplitude = cfg.goals.amplitude * [1; 1];', ...
    'maximum = amplitude + 0.10;', ...
    'stopReason = ''target_reached'';', ...
    'paramMatrix = [params(1), atValues(1); targetKd, atValues(2)];', ...
    'result = make_result({''Kd'', ''AT''}, paramMatrix(end, :), period(end), amplitude(end), maximum(end), make_path({''Kd'', ''AT''}, paramMatrix, period, amplitude, maximum, stopReason));', ...
    'end', ...
    '', ...
    'function result = make_result(paramNames, params, period, amplitude, maximum, path)', ...
    'orbit = make_orbit(period, params, amplitude, maximum);', ...
    'result = struct();', ...
    'result.params = reshape(params, 1, []);', ...
    'result.orbit = orbit;', ...
    'result.path = path;', ...
    'result.measures = struct(''period'', period, ''amplitude'', amplitude, ''maximum'', maximum);', ...
    'result.solverView = struct(''params'', reshape(params, 1, []));', ...
    'result.derivedView = struct(''period'', period, ''obsAmp'', amplitude, ''obsMax'', maximum, ''obsMin'', maximum - 2 * amplitude);', ...
    'end', ...
    '', ...
    'function path = make_path(paramNames, paramMatrix, period, amplitude, maximum, stopReason)', ...
    'path = struct();', ...
    'path.paramNames = paramNames;', ...
    'path.paramMatrix = paramMatrix;', ...
    'path.period = period(:);', ...
    'path.obsAmplitude = amplitude(:);', ...
    'path.obsMax = maximum(:);', ...
    'path.obsMin = path.obsMax - 2 * path.obsAmplitude;', ...
    'path.lambda = linspace(0, 1, size(paramMatrix, 1)).'';', ...
    'path.directConditionEstimate = ones(size(paramMatrix, 1), 1);', ...
    'path.finalConditionEstimate = ones(size(paramMatrix, 1), 1);', ...
    'path.success = true(size(paramMatrix, 1), 1);', ...
    'path.stopReason = stopReason;', ...
    'path.stopLambda = 1;', ...
    'path.stopTriggerValue = NaN;', ...
    'end', ...
    '', ...
    'function orbit = make_orbit(period, params, amplitude, maximum)', ...
    't = linspace(0, period, 8).'';', ...
    'ptot = maximum - amplitude + amplitude * (1 + sin(2 * pi * t / max(period, eps)));', ...
    'pc = 0.6 * ptot;', ...
    'pn = 0.4 * ptot;', ...
    'orbit = struct();', ...
    'orbit.t = t;', ...
    'orbit.y = [ptot, pc, pn];', ...
    'orbit.obs = ptot;', ...
    'orbit.period = period;', ...
    'orbit.params = params;', ...
    'orbit.amplitude = amplitude;', ...
    'orbit.yMax = maximum;', ...
    'orbit.yMin = maximum - 2 * amplitude;', ...
    'end'};
fprintf(fid, '%s\n', lines{:});
end
