function tests = test_flexible_modulator_iso_curve_cache_refactor
%TEST_FLEXIBLE_MODULATOR_ISO_CURVE_CACHE_REFACTOR Regression coverage for Fig. 3 cache refactor.

tests = functiontests(localfunctions);
end

function setup(testCase)
global RUN_MODULATION_TASK_LOG FLEX_FIND_ORBIT_LOG
RUN_MODULATION_TASK_LOG = {};
FLEX_FIND_ORBIT_LOG = {};

stubDir = tempname;
mkdir(stubDir);
mkdir(fullfile(stubDir, '+flexmod'));
write_run_modulation_task_stub(stubDir);
write_flexmod_find_orbit_stub(fullfile(stubDir, '+flexmod'));
write_base_bifurcation_stub(stubDir);

flexmod.ensure_paths();
addpath(stubDir, '-begin');
clear run_modulation_task
clear flexmod.find_orbit
clear base_bifurcation_curve

testCase.TestData.stubDir = stubDir;
testCase.TestData.cleanupPath = onCleanup(@() cleanup_stub_dir(stubDir));
end

function teardown(~)
global RUN_MODULATION_TASK_LOG FLEX_FIND_ORBIT_LOG
RUN_MODULATION_TASK_LOG = {};
FLEX_FIND_ORBIT_LOG = {};
close all force
end

function testBuildFig3CurveCachesAndIndependentMarks(testCase)
global RUN_MODULATION_TASK_LOG

cfg = make_test_cfg();
curveData3c = build_fig3c_data(cfg);
curveLogs3c = RUN_MODULATION_TASK_LOG;
verifyEqual(testCase, numel(curveData3c.curves), 2);
verifyEqual(testCase, numel(curveData3c.curveFiles), 2);
verifyTrue(testCase, all(cellfun(@isfile, curveData3c.curveFiles)));
verifyEqual(testCase, numel(filter_logs(curveLogs3c, {'period', 'amplitude'})), 2);
verifyEqual(testCase, numel(filter_logs(curveLogs3c, {'period', 'I1'})), 4);

RUN_MODULATION_TASK_LOG = {};
markData3c = build_fig3c_marks(cfg);
verifyTrue(testCase, all(cellfun(@isfile, markData3c.markFiles)));
markLogs3c = RUN_MODULATION_TASK_LOG;
verifyEqual(testCase, numel(markLogs3c), numel(cfg.fig3c.markAmplitudes));
for i = 1:numel(markLogs3c)
    verifyEqual(testCase, markLogs3c{i}.startParams, cfg.fig3c.markSeeds(i, :), 'AbsTol', 1e-12);
end

RUN_MODULATION_TASK_LOG = {};
curveData3d = build_fig3d_data(cfg);
curveLogs3d = RUN_MODULATION_TASK_LOG;
verifyEqual(testCase, numel(curveData3d.curves), 2);
verifyEqual(testCase, numel(curveData3d.curveFiles), 2);
verifyTrue(testCase, all(cellfun(@isfile, curveData3d.curveFiles)));
verifyEqual(testCase, numel(filter_logs(curveLogs3d, {'amplitude', 'period'})), 2);
verifyEqual(testCase, numel(filter_logs(curveLogs3d, {'amplitude', 'I1'})), 4);

RUN_MODULATION_TASK_LOG = {};
markData3d = build_fig3d_marks(cfg);
verifyTrue(testCase, all(cellfun(@isfile, markData3d.markFiles)));
markLogs3d = RUN_MODULATION_TASK_LOG;
verifyEqual(testCase, numel(markLogs3d), numel(cfg.fig3d.markPeriods));
for i = 1:numel(markLogs3d)
    verifyEqual(testCase, markLogs3d{i}.startParams, cfg.fig3d.markSeeds(i, :), 'AbsTol', 1e-12);
end
end

function testReproduceFig3UsesExistingPerCurveCaches(testCase)
global RUN_MODULATION_TASK_LOG

cfg = make_test_cfg();
build_fig3c_data(cfg);
build_fig3c_marks(cfg);
build_fig3d_data(cfg);
build_fig3d_marks(cfg);

RUN_MODULATION_TASK_LOG = {};
reproduce_fig3c(cfg);
verifyEqual(testCase, numel(RUN_MODULATION_TASK_LOG), 0);

RUN_MODULATION_TASK_LOG = {};
reproduce_fig3d(cfg);
verifyEqual(testCase, numel(RUN_MODULATION_TASK_LOG), 0);
end

function testReproduceAllFig3BuildsOnEmptyCacheRoot(testCase)
cfg = make_test_cfg();
result = reproduce_all_fig3(cfg);

verifyTrue(testCase, isfile(flexmod.curve_cache_file(cfg, 'fig3c', 'period', cfg.fig3c.periods(1))));
verifyTrue(testCase, isfile(flexmod.curve_cache_file(cfg, 'fig3d', 'amplitude', cfg.fig3d.amplitudes(1))));
verifyTrue(testCase, isfile(flexmod.mark_cache_file(cfg, 'fig3c', 'amplitude_01')));
verifyTrue(testCase, isfile(flexmod.mark_cache_file(cfg, 'fig3d', 'period_01')));

verifyTrue(testCase, isgraphics(result.fig3b.figure));
verifyTrue(testCase, isgraphics(result.fig3c.figure));
verifyTrue(testCase, isgraphics(result.fig3d.figure));
verifyTrue(testCase, isgraphics(result.fig3f.figure));
end

function entries = filter_logs(logEntries, goalOrder)
mask = cellfun(@(entry) isequal(entry.goalOrder, goalOrder), logEntries);
entries = logEntries(mask);
end

function cfg = make_test_cfg()
cfg = default_config();
cfg.grid.I1Values = [0.8, 1.0];
cfg.grid.ETValues = [0.8, 1.0];
cfg.grid.seriesET = [0.9, 1.0, 1.1];
cfg.fig3c.periods = [80, 84];
cfg.fig3c.amplitudes = [2.5, 2.9];
cfg.fig3c.markPeriod = 80;
cfg.fig3c.markAmplitudes = [2.0, 2.5];
cfg.fig3c.markSeeds = [0.92, 1.05; 1.00, 1.15];
cfg.fig3d.amplitudes = [2.1, 2.7];
cfg.fig3d.periods = [80, 90];
cfg.fig3d.markAmplitude = 2.1;
cfg.fig3d.markPeriods = [60, 80];
cfg.fig3d.markSeeds = [0.95, 1.10; 1.00, 1.20];
cfg.fig3d.maxParamJump = [1, 1];
cfg.fig3d.maxPeriodJump = 100;
cfg.fmam.dlambdaCap = 0.25;

tempRoot = tempname;
mkdir(tempRoot);
cfg.io.cacheDir = fullfile(tempRoot, 'cache');
cfg.io.figureDir = fullfile(tempRoot, 'figure');

seed_bifurcation_cache(cfg.io.cacheDir);
end

function seed_bifurcation_cache(cacheDir)
data = struct();
data.hopfCurves = {};
data.lpCurves = {};
if ~isfolder(cacheDir)
    mkdir(cacheDir);
end
save(fullfile(cacheDir, 'base_bifurcation_matcont_v1.mat'), 'data', '-v7.3');
end

function cleanup_stub_dir(stubDir)
if isfolder(stubDir)
    rmpath(stubDir);
    clear run_modulation_task
    clear flexmod.find_orbit
    clear base_bifurcation_curve
    try
        rmdir(stubDir, 's');
    catch
    end
end
end

function write_run_modulation_task_stub(stubDir)
stubPath = fullfile(stubDir, 'run_modulation_task.m');
fid = fopen(stubPath, 'w');
assert(fid >= 0, 'Failed to create run_modulation_task stub.');
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

lines = { ...
    'function result = run_modulation_task(cfg)', ...
    'global RUN_MODULATION_TASK_LOG', ...
    'if isempty(RUN_MODULATION_TASK_LOG), RUN_MODULATION_TASK_LOG = {}; end', ...
    'RUN_MODULATION_TASK_LOG{end + 1} = struct(''startParams'', reshape(cfg.startParams, 1, []), ''goalOrder'', {cfg.goalOrder}, ''goals'', cfg.goals);', ...
    'goalOrder = cfg.goalOrder;', ...
    'if isequal(goalOrder, {''period'', ''amplitude''})', ...
    '    result = make_period_amplitude_result(cfg);', ...
    'elseif isequal(goalOrder, {''period'', ''I1''})', ...
    '    result = make_period_i1_branch(cfg);', ...
    'elseif isequal(goalOrder, {''amplitude'', ''period''})', ...
    '    result = make_amplitude_period_seed(cfg);', ...
    'elseif isequal(goalOrder, {''amplitude'', ''I1''})', ...
    '    result = make_amplitude_i1_branch(cfg);', ...
    'else', ...
    '    error(''test:UnexpectedGoalOrder'', ''Unexpected goalOrder in stub.'');', ...
    'end', ...
    'end', ...
    '', ...
    'function result = make_period_amplitude_result(cfg)', ...
    'params = reshape(cfg.startParams, 1, []);', ...
    'if isfield(cfg, ''modelType'') && strcmp(cfg.modelType, ''temperature'')', ...
    '    pathParams = [params; params + [0.1, -1.5]; params + [0.2, -3.0]];', ...
    'else', ...
    '    pathParams = [params; params + [0.05, 0.08]; params + [0.10, 0.12]];', ...
    'end', ...
    'period = linspace(cfg.goals.period + 2, cfg.goals.period, size(pathParams, 1)).'';', ...
    'amplitude = linspace(max(cfg.goals.amplitude - 0.5, 0.1), cfg.goals.amplitude, size(pathParams, 1)).'';', ...
    'result = make_result(pathParams(end, :), period(end), amplitude(end), make_path(pathParams, period, amplitude, ''target_reached''));', ...
    'end', ...
    '', ...
    'function result = make_period_i1_branch(cfg)', ...
    'params = reshape(cfg.startParams, 1, []);', ...
    'targetI1 = cfg.goals.I1;', ...
    'etValues = [params(2); params(2) + 0.12 * sign(targetI1 - params(1) + eps)];', ...
    'paramMatrix = [params(1), etValues(1); targetI1, etValues(2)];', ...
    'period = cfg.goals.period * ones(2, 1);', ...
    'amplitude = [1.8; 2.4] + 0.2 * sign(targetI1 - params(1));', ...
    'result = make_result(paramMatrix(end, :), period(end), amplitude(end), make_path(paramMatrix, period, amplitude, ''target_reached''));', ...
    'end', ...
    '', ...
    'function result = make_amplitude_period_seed(cfg)', ...
    'params = reshape(cfg.startParams, 1, []);', ...
    'period = cfg.goals.period;', ...
    'amplitude = cfg.goals.amplitude;', ...
    'result = make_result(params, period, amplitude, make_path([params; params + [0.02, 0.02]], [period; period], [amplitude; amplitude], ''target_reached''));', ...
    'end', ...
    '', ...
    'function result = make_amplitude_i1_branch(cfg)', ...
    'params = reshape(cfg.startParams, 1, []);', ...
    'targetI1 = cfg.goals.I1;', ...
    'etValues = [params(2); params(2) + 0.10 * sign(targetI1 - params(1) + eps)];', ...
    'paramMatrix = [params(1), etValues(1); targetI1, etValues(2)];', ...
    'period = [cfg.goals.amplitude * 20 + 18; cfg.goals.amplitude * 20 + 20];', ...
    'amplitude = cfg.goals.amplitude * [1; 1];', ...
    'result = make_result(paramMatrix(end, :), period(end), amplitude(end), make_path(paramMatrix, period, amplitude, ''target_reached''));', ...
    'end', ...
    '', ...
    'function result = make_result(params, period, amplitude, path)', ...
    'orbit = make_orbit(period, params, amplitude);', ...
    'result = struct();', ...
    'result.params = reshape(params, 1, []);', ...
    'result.orbit = orbit;', ...
    'result.path = path;', ...
    'result.measures = struct(''period'', period, ''amplitude'', amplitude, ''y_max'', amplitude + 3, ''y_min'', 3 - amplitude);', ...
    'result.solverView = struct(''params'', reshape(params, 1, []));', ...
    'result.derivedView = struct(''period'', period, ''varAmp'', [0 amplitude], ''varMax'', [0 amplitude + 3], ''varMin'', [0 3 - amplitude]);', ...
    'end', ...
    '', ...
    'function path = make_path(paramMatrix, period, amplitude, stopReason)', ...
    'path = struct();', ...
    'path.paramNames = {''I1'', ''ET''};', ...
    'path.paramMatrix = paramMatrix;', ...
    'path.period = period(:);', ...
    'path.amplitude = amplitude(:);', ...
    'path.yMax = amplitude(:) + 3;', ...
    'path.yMin = 3 - amplitude(:);', ...
    'path.lambda = linspace(0, 1, size(paramMatrix, 1)).'';', ...
    'path.directConditionEstimate = ones(size(paramMatrix, 1), 1);', ...
    'path.finalConditionEstimate = ones(size(paramMatrix, 1), 1);', ...
    'path.success = true(size(paramMatrix, 1), 1);', ...
    'path.stopReason = stopReason;', ...
    'path.stopLambda = 1;', ...
    'path.stopTriggerValue = NaN;', ...
    'end', ...
    '', ...
    'function orbit = make_orbit(period, params, amplitude)', ...
    't = linspace(0, max(period, 1), 8).'';', ...
    'y = 3 + amplitude * sin(2 * pi * t / max(period, eps));', ...
    'orbit = struct();', ...
    'orbit.t = t;', ...
    'orbit.y = [zeros(size(t)), y];', ...
    'orbit.period = period;', ...
    'orbit.params = params;', ...
    'orbit.amplitude = amplitude;', ...
    'orbit.yMax = max(y);', ...
    'orbit.yMin = min(y);', ...
    'orbit.success = true;', ...
    'orbit.message = '''';', ...
    'end'};
fprintf(fid, '%s\n', lines{:});
end

function write_flexmod_find_orbit_stub(packageDir)
stubPath = fullfile(packageDir, 'find_orbit.m');
fid = fopen(stubPath, 'w');
assert(fid >= 0, 'Failed to create flexmod.find_orbit stub.');
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

lines = { ...
    'function orbit = find_orbit(~, params, ~, ~)', ...
    'global FLEX_FIND_ORBIT_LOG', ...
    'if isempty(FLEX_FIND_ORBIT_LOG), FLEX_FIND_ORBIT_LOG = {}; end', ...
    'FLEX_FIND_ORBIT_LOG{end + 1} = reshape(params, 1, []);', ...
    'period = 40 + 10 * params(1) + 5 * params(2);', ...
    'amplitude = 1 + 0.5 * params(1) + 0.2 * params(2);', ...
    't = linspace(0, period, 12).'';', ...
    'y = 3 + amplitude * sin(2 * pi * t / max(period, eps));', ...
    'orbit = struct();', ...
    'orbit.success = true;', ...
    'orbit.message = '''';', ...
    'orbit.t = t;', ...
    'orbit.y = [zeros(size(t)), y];', ...
    'orbit.period = period;', ...
    'orbit.amplitude = amplitude;', ...
    'orbit.yMax = max(y);', ...
    'orbit.yMin = min(y);', ...
    'end'};
fprintf(fid, '%s\n', lines{:});
end

function write_base_bifurcation_stub(stubDir)
stubPath = fullfile(stubDir, 'base_bifurcation_curve.m');
fid = fopen(stubPath, 'w');
assert(fid >= 0, 'Failed to create base_bifurcation_curve stub.');
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

lines = { ...
    'function bifurcation = base_bifurcation_curve(cfg)', ...
    'bifurcation = struct();', ...
    'bifurcation.visibleHopfCurves = {};', ...
    'bifurcation.visibleLpCurves = {};', ...
    'bifurcation.yRange = [min(cfg.grid.ETValues), max(cfg.grid.ETValues)];', ...
    'end'};
fprintf(fid, '%s\n', lines{:});
end
