function tests = test_legacy_boundary_contracts
tests = functiontests(localfunctions);
end

function testFmamStateOpsDoesNotReferenceUtilsImpl(testCase)
source = fileread(fullfile(repo_root(), 'fmam_state_ops.m'));
verifyFalse(testCase, contains(source, 'utils.state_ops'));
end

function testUtilsStateOpsShimIsRemoved(testCase)
verifyFalse(testCase, isfile(fullfile(repo_root(), '+utils', 'state_ops.m')));
end

function testProductionCodeAvoidsLegacyStateCompatibilityEntrypoints(testCase)
files = { ...
    fullfile(repo_root(), 'FMAM_ODE.m'), ...
    fullfile(repo_root(), 'assemble_newton_linear_system.m'), ...
    fullfile(repo_root(), 'fmam_state_ops.m'), ...
    fullfile(repo_root(), 'state.m'), ...
    fullfile(repo_root(), 'Circadian', '+circadian', 'run_fmam_task.m'), ...
    fullfile(repo_root(), 'flexible_modulators', '+flexmod', 'run_fmam_task.m')};

patterns = {'state.Lconst', 'state.LphiConst', ...
    'state.defaultDiscretization(', 'state.defaultExtremaSearch(', ...
    'state.FindExtreme(', 'state.normalizeDiscretization(', ...
    'state.normalizeExtremaSearch('};
for i = 1:numel(files)
    source = fileread(files{i});
    for j = 1:numel(patterns)
        verifyFalse(testCase, contains(source, patterns{j}), ...
            sprintf('Unexpected legacy state compatibility reference in %s: %s', files{i}, patterns{j}));
    end
end
end

function testActiveProductionEntrypointsDoNotPassStateObjectsIntoFMAMODE(testCase)
files = { ...
    fullfile(repo_root(), 'Longevity', 'build_longevity_modulation_cache.m'), ...
    fullfile(repo_root(), 'RLT_circuit', 'Modulation_observable.m'), ...
    fullfile(repo_root(), 'RLT_circuit', 'Modulation_phase.m'), ...
    fullfile(repo_root(), 'RLT_circuit', 'Modulation_bi_target', 'Modulation_bi_target.m'), ...
    fullfile(repo_root(), 'RLT_circuit', 'Modulation_tri_target', 'Modulation_tri_target.m'), ...
    fullfile(repo_root(), 'RLT_circuit', 'parameter_inference', 'params_inf.m'), ...
    fullfile(repo_root(), 'RLT_circuit', 'parameter_inference', 'draw_params.m')};

patterns = { ...
    'targetInput = targetState;', ...
    'FMAM_ODE(sys,obs,State,', ...
    'FMAM_ODE(sys, obs, State,', ...
    'FMAM_ODE(sys,[],State,', ...
    'FMAM_ODE(ctx.sys, ctx.obs, stateObj,'};

for i = 1:numel(files)
    source = fileread(files{i});
    for j = 1:numel(patterns)
        verifyFalse(testCase, contains(source, patterns{j}), ...
            sprintf('Unexpected legacy FMAM_ODE state-input pattern in %s: %s', files{i}, patterns{j}));
    end
end
end

function testDefaultConfigsRemainSeparated(testCase)
extremaSearch = fmam_state_ops.defaultExtremaSearchSettings();

defaultCfg = fmam_state_defaults.defaultDiscretization();
verifyEqual(testCase, fmam_state_defaults.timeResampleCount, defaultCfg.reconstruction.timeResampleCount);
verifyEqual(testCase, fmam_state_defaults.phaseSampleCount, defaultCfg.reconstruction.phaseSampleCount);
verifyEqual(testCase, extremaSearch.maxRefinementRounds, fmam_state_ops.maxRefinementRounds);
verifyEqual(testCase, extremaSearch.extremaResidualTolerance, fmam_state_ops.extremaResidualTolerance);
end

function root = repo_root()
root = fileparts(fileparts(mfilename('fullpath')));
end
