function tests = test_matcont_periodic_orbit_backend
%TEST_MATCONT_PERIODIC_ORBIT_BACKEND Regression checks for the MATCONT backend.

tests = functiontests(localfunctions);
end

function testOrbitmatcontBackend(testCase)
rootDir = fileparts(fileparts(mfilename('fullpath')));
matcontRoot = fullfile(rootDir, 'MatCont7p6');
assumeTrue(testCase, ...
    isfile(fullfile(matcontRoot, 'Continuer', 'cont.m')), ...
    'MatCont is an optional untracked dependency; skipping backend regression test.');
addpath(rootDir);
addpath(fullfile(rootDir, 'PO_extract'));
addpath(genpath(matcontRoot));

opts = struct( ...
    'tspan', [0, 300], ...
    'transientFraction', 0.8, ...
    'matcont_root', matcontRoot, ...
    'matcont_active_parameter', 2, ...
    'matcont_tolerance', 1e-2, ...
    'matcont_parameter_tolerance', 1e-3, ...
    'matcont_window_timespan', 10, ...
    'extractNumPoints', 120);

directResult = solve_periodic_orbit_matcont(@adaptx, [0.3; 0.5; -0.1], [1; 0.8], opts);
verifyTrue(testCase, directResult.has_orbit, 'Expected orbit extraction to succeed for MATCONT odefile input.');
verifyEqual(testCase, char(directResult.status), 'converged_periodic_orbit', ...
    'Expected converged_periodic_orbit status.');
verifyTrue(testCase, directResult.success, 'Expected successful extraction for MATCONT odefile input.');
verifyGreaterThan(testCase, directResult.period, 5, 'Expected refined period to stay in a reasonable range.');
verifyLessThan(testCase, directResult.period, 9, 'Expected refined period to stay in a reasonable range.');
verifyEqual(testCase, size(directResult.orbit_y, 1), opts.extractNumPoints, ...
    'Expected extracted orbit to be resampled to extractNumPoints.');
verifyLessThanOrEqual(testCase, ...
    abs(directResult.output_active_parameter_value - directResult.input_active_parameter_value), ...
    opts.matcont_parameter_tolerance, ...
    'Expected the returned active parameter to match the input parameter within tolerance.');
verifyNotEmpty(testCase, directResult.output_parameter_values, ...
    'Expected output_parameter_values to be populated.');
verifyGreaterThan(testCase, strlength(string(directResult.parameter_status)), 0, ...
    'Expected parameter_status to be reported.');

routerOpts = opts;
routerOpts.orbit_solver = 'matcont';
routerOpts.matcont_odefile = @adaptx;
routerResult = extract_periodic_orbit(@adaptx, [0.3; 0.5; -0.1], [1; 0.8], routerOpts);
verifyTrue(testCase, routerResult.has_orbit && routerResult.success, ...
    'Unified entrypoint should forward orbit_solver=matcont to the MATCONT backend.');

handles = adaptx();
rhs = @(t, y, p) handles{2}(t, y, p(1), p(2));
wrappedOpts = opts;
wrappedOpts.matcont_odefile = @adaptx;
wrappedResult = solve_periodic_orbit_matcont(rhs, [0.3; 0.5; -0.1], [1; 0.8], wrappedOpts);
verifyTrue(testCase, wrappedResult.has_orbit, 'Expected wrapped RHS + matcont_odefile flow to succeed.');
verifyTrue(testCase, wrappedResult.success, 'Expected wrapped RHS + matcont_odefile flow to succeed.');
verifyLessThan(testCase, abs(wrappedResult.period - directResult.period), 0.5, ...
    'Expected wrapped and direct MATCONT flows to agree on the period.');
verifyLessThanOrEqual(testCase, ...
    abs(wrappedResult.output_active_parameter_value - wrappedResult.input_active_parameter_value), ...
    wrappedOpts.matcont_parameter_tolerance, ...
    'Expected wrapped flow to return the input active parameter within tolerance.');

verifyError(testCase, ...
    @() solve_periodic_orbit_matcont(rhs, [0.3; 0.5; -0.1], [1; 0.8], rmfield(wrappedOpts, 'matcont_odefile')), ...
    'orbitmatcont:MissingMatcontOdefile', ...
    'Expected a MissingMatcontOdefile error when matcont_odefile is omitted for a plain RHS.');

badNcolOpts = wrappedOpts;
badNcolOpts.matcont_ncol = 8;
verifyError(testCase, ...
    @() solve_periodic_orbit_matcont(rhs, [0.3; 0.5; -0.1], [1; 0.8], badNcolOpts), ...
    'orbitmatcont:InvalidNcol', ...
    'Expected an InvalidNcol error when ncol falls outside the MATCONT-supported range.');

strictOpts = wrappedOpts;
strictOpts.matcont_parameter_tolerance = 1e-6;
strictResult = solve_periodic_orbit_matcont(rhs, [0.3; 0.5; -0.1], [1; 0.8], strictOpts);
verifyTrue(testCase, strictResult.success, ...
    'Expected userfunction-based target continuation to recover the input parameter at 1e-6 tolerance.');
verifyLessThanOrEqual(testCase, ...
    abs(strictResult.output_active_parameter_value - strictResult.input_active_parameter_value), ...
    strictOpts.matcont_parameter_tolerance, ...
    'Expected strictResult to satisfy the tighter active-parameter tolerance.');
verifyEqual(testCase, strictResult.diagnostics.seedSource, "internal", ...
    'MATCONT backend should now use only the internal preprocessing path.');
verifyTrue(testCase, isfield(strictResult.raw, 'pilot') && isfield(strictResult.raw, 'window'), ...
    'Internal preprocessing should keep pilot and window trajectories in diagnostics.');
verifyLessThanOrEqual(testCase, ...
    abs(strictResult.diagnostics.cycleWindowDuration - strictOpts.matcont_window_timespan), ...
    1e-12, ...
    'matcont_window_timespan should still override the internal window length.');

unsupportedMatcontCases = { ...
    'seed_orbit', struct('t', [0; 1], 'y', [0 0 0; 0 0 0], 'period', 1); ...
    'seed_quality_reference', struct('period', 1); ...
    'unsupported_flag', true};
for k = 1:size(unsupportedMatcontCases, 1)
    unsupportedOpts = wrappedOpts;
    unsupportedOpts.(unsupportedMatcontCases{k, 1}) = unsupportedMatcontCases{k, 2};
    verifyError(testCase, ...
        @() solve_periodic_orbit_matcont(rhs, [0.3; 0.5; -0.1], [1; 0.8], unsupportedOpts), ...
        'orbitmatcont:InvalidOptions', ...
        'Expected an InvalidOptions error when unsupported MATCONT options are passed.');
end

failureOpts = wrappedOpts;
failureOpts.matcont_parameter_tolerance = 1e-12;
failureOpts.matcont_return_max_points = 2;
failureOpts.matcont_return_scan_both_directions = false;
verifyError(testCase, ...
    @() solve_periodic_orbit_matcont(rhs, [0.3; 0.5; -0.1], [1; 0.8], failureOpts), ...
    'orbitmatcont:ParameterReturnFailed', ...
    'Expected a ParameterReturnFailed error when the target continuation budget is too short to reach the userfunction zero.');
end
