function cfg = po_matcont_default_config()
%PO_MATCONT_DEFAULT_CONFIG Default MATCONT-specific options for PO_extract.

cfg = struct( ...
    'solver_name', 'ode45', ...
    'solver_tol', struct('RelTol', 1e-7, 'AbsTol', 1e-9), ...
    'transientFraction', 0.5, ...
    'extractNumPoints', 1000, ...
    'computeQualityDiagnostics', false, ...
    'matcont_root', default_matcont_root(), ...
    'matcont_odefile', [], ...
    'matcont_active_parameter', [], ...
    'matcont_parameter_values', [], ...
    'matcont_ntst', 80, ...
    'matcont_ncol', 4, ...
    'matcont_tolerance', 1e-4, ...
    'matcont_window_timespan', [], ...
    'matcont_cycle_window_factor', 1.25, ...
    'matcont_options', struct('Adapt', 5), ...
    'matcont_parameter_tolerance', 1e-6, ...
    'matcont_return_max_points', 1000, ...
    'matcont_return_scan_both_directions', true);
end

function root = default_matcont_root()
poDir = fileparts(mfilename('fullpath'));
root = fullfile(fileparts(poDir), 'MatCont7p6');
end
