function orbit = orbit_from_state(stateLike, params)
params = reshape(params, 1, []);
t = stateLike.t(:);
y = stateLike.TS_var;
period = stateLike.period;

if isempty(t) || isempty(y) || ~(isfinite(period) && period > 0)
    error('circadian:InvalidStateOrbit', ...
        'Cannot reconstruct orbit from state because the time series or period is invalid.');
end

if isfield(stateLike, 'TS_obs') && ~isempty(stateLike.TS_obs)
    obs = stateLike.TS_obs(:, 1);
else
    obs = y(:, 2) + y(:, 3);
end

if abs(t(end) - period) > eps(max(period, 1))
    t = [t; period];
    y = [y; y(1, :)];
    obs = [obs; obs(1)];
end

orbit = struct( ...
    'success', true, ...
    'message', 'Reconstructed directly from FMAM state.', ...
    't', t, ...
    'y', y, ...
    'obs', obs, ...
    'period', period, ...
    'amplitude', 0.5 * (max(obs) - min(obs)), ...
    'yMax', max(obs), ...
    'yMin', min(obs), ...
    'params', params, ...
    'result', struct('source', 'state'));
end
