clear
clc

%% User settings
settings = struct();
settings.randomSeed = 0;
% netName options: 'ER', 'BA', 'SW'
settings.netName = 'SW';
settings.weightPer = 0.3;
settings.nPerturbedEdges = 50;
% Options: 'prefix', 'uniformRandomWithoutReplacement', 'uniformRandomWithReplacement'
settings.perturbedNodeSelectionMode = 'prefix';
% Options: 'prefix', 'uniformRandomWithoutReplacement', 'uniformRandomWithReplacement'
settings.inputNodeSelectionMode = 'uniformRandomWithoutReplacement';
settings.solverName = 'ode15s';
settings.searchWindow = 5000;
settings.network = struct( ...
    'N', 100, ...
    'degAvg', 5, ...
    'K', 1, ...
    'baSeedDegree', 5, ...
    'swNeighborCount', 2, ...
    'swRewireProb', 0.15);
settings.modelParams = struct( ...
    'theta', 0.5, ... % or theta = 0.5
    'gamma', 1, ... % or gamma = 1
    'epsilon', 1e-2, ... 
    'tau', 1, ... 
    'I', 0.38); % or I = 0.5

modelSpec = create_model_spec(settings.modelParams, settings.searchWindow);
networkexp.run_single_experiment(settings, modelSpec);

function modelSpec = create_model_spec(modelParams, searchWindow)
modelSpec = struct( ...
    'name', 'FHN', ...
    'makeInitialState', @(N) 0.21*ones(2 * N, 1), ...
    'buildParams', @(omega) { ...
        modelParams.theta, ...
        modelParams.gamma, ...
        modelParams.epsilon, ...
        modelParams.tau, ...
        modelParams.I, ...
        sparse(omega)}, ...
    'buildSolverOptions', @(params) networkexp.build_fhn_orbit_detection_options( ...
        networkexp.build_fhn_solver_options(params), searchWindow), ...
    'rhs', @fhn_rhs);
end

function dydt = fhn_rhs(~, x, params)
theta = params{1};
gamma = params{2};
epsilon = params{3};
tau = params{4};
I = params{5};
matAdj = sparse(params{6});

V = 0;
N = size(matAdj, 1);
dydt = zeros(2 * N, 1);
v = x(1:N);
w = x(N + 1:end);
sigma = 1 ./ (1 + exp(-tau * (v - V)));

dydt(1:N) = v .* (v - theta) .* (1 - v) - w + I + matAdj * sigma;
dydt(N + 1:end) = epsilon * (v - gamma * w);
end
