clear
clc

%% User settings
settings = struct();
settings.randomSeed = 1;

% netName options: 'ER', 'BA', 'SW'
settings.netName = 'ER'; 

settings.weightPer = 0.03;
settings.nPerturbedEdges = 50;

% Options: 'prefix', 'uniformRandomWithoutReplacement', 'uniformRandomWithReplacement'
settings.perturbedNodeSelectionMode = 'prefix';

% Options: 'prefix', 'uniformRandomWithoutReplacement', 'uniformRandomWithReplacement'
settings.inputNodeSelectionMode = 'uniformRandomWithoutReplacement';

settings.solverName = 'ode15s';
settings.searchWindow = 3000;
settings.network = struct( ...
    'N', 100, ...
    'degAvg', 5, ...
    'K', 0.1, ...
    'baSeedDegree', 5, ...
    'swNeighborCount', 2, ...
    'swRewireProb', 0.15);
settings.modelParams = struct( ...
    'd_p', 0.01, ...
    'd_E', 1, ...
    'k_m', 0.5, ...
    'S', 0.7, ...
    'K_d', 1, ...
    'n', 4, ...
    'd_m', 1, ...
    'epsilon', 5e-2);

modelSpec = struct( ...
    'name', 'GRN', ...
    'makeInitialState', @(N) [50*ones(N, 1);0*ones(N,1)], ...
    'buildParams', @(omega) { ...
        settings.modelParams.d_p, ...
        settings.modelParams.d_E, ...
        settings.modelParams.k_m, ...
        settings.modelParams.epsilon, ...
        settings.modelParams.S, ...
        settings.modelParams.K_d, ...
        settings.modelParams.n, ...
        settings.modelParams.d_m, ...
        sparse(omega)}, ...
    'buildSolverOptions', @networkexp.build_grn_solver_options, ...
    'rhs', @grn_rhs);

networkexp.run_single_experiment(settings, modelSpec);




function dydt = grn_rhs(~, y, params)
d_p = params{1};
d_E = params{2};
k_m = params{3};
epsilon = params{4};
S = params{5};
K_d = params{6};
n = params{7};
d_m = params{8};
matAdj = sparse(params{9});

N = size(matAdj, 1);
dydt = zeros(2 * N, 1);
p = y(1:N);
m = y(N + 1:end);
g = p ./ (1 + p);
interaction = m .* (matAdj * g);

dydt(1:N) = m - d_p * p - d_E * p ./ (k_m + p + p.^2) + interaction;
dydt(N + 1:end) = epsilon * (S * K_d^n ./ (K_d^n + p.^n) - d_m * m);
end
