function F = FHN_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:32

epsilon = in2(:,4);
f11 = in2(:,5);
f12 = in2(:,6);
f21 = in2(:,7);
gamma_ = in2(:,2);
theta = in2(:,1);
v = in1(:,1);
t2 = f11.*1.0;
t3 = -v;
t4 = v-1.0;
t5 = t3+theta;
A = reshape([t2+t3.*t4+t4.*t5+t5.*v,epsilon+f21.*1.0,f12.*1.0-1.0,-t2-epsilon.*gamma_],[2,2]);
end

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:32

epsilon = in2(:,4);
gamma_ = in2(:,2);
v = in1(:,1);
w = in1(:,2);
t2 = v-3.068e-1;
J1 = reshape([v.*(v-1.0),0.0,0.0,-epsilon.*w,1.0,0.0,0.0,v-gamma_.*w,t2,-w+1.227e-1,w-1.227e-1,0.0,0.0,t2],[2,7]);
end

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:33

theta = in2(:,1);
v = in1(:,1);
v11 = in3(1,:);
v21 = in4(1,:);
B = [v11.*v21.*(theta.*2.0-v.*6.0+2.0);0.0];
end

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:33

p12 = in3(2,:);
p14 = in3(4,:);
p22 = in4(2,:);
p24 = in4(4,:);
w = in1(:,2);
J2 = [0.0;-p12.*p24.*w-p14.*p22.*w];
end

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:33

epsilon = in2(:,4);
gamma_ = in2(:,2);
p11 = in4(1,:);
p12 = in4(2,:);
p14 = in4(4,:);
p15 = in4(5,:);
p16 = in4(6,:);
p17 = in4(7,:);
v = in1(:,1);
v11 = in3(1,:);
v12 = in3(2,:);
t2 = v11.*1.0;
A1 = [p15.*t2+p16.*v12.*1.0+p11.*v11.*(v.*2.0-1.0);p17.*t2-p15.*v12.*1.0+p14.*(t2-gamma_.*v12)-epsilon.*p12.*v12];
end

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:33

v11 = in3(1,:);
v21 = in4(1,:);
v31 = in5(1,:);
C = [v11.*v21.*v31.*-6.0;0.0];
end

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:33

J3 = [0.0;0.0];
end

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:33

p11 = in5(1,:);
v11 = in3(1,:);
v21 = in4(1,:);
B1 = [p11.*v11.*v21.*2.0;0.0];
end

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-09-28 15:13:33

p12 = in4(2,:);
p14 = in4(4,:);
p22 = in5(2,:);
p24 = in5(4,:);
v12 = in3(2,:);
A2 = [0.0;-p12.*p24.*v12-p14.*p22.*v12];
end

