function cache = generate_extended_fig2b_data()
scriptDir = fileparts(mfilename('fullpath'));
cacheFile = fullfile(scriptDir, 'extended_fig2b_cache.mat');

% The paper's reported alpha-target parameters reproduce min(S,H) = (300, 250)
% under direct deterministic orbit extraction, so this generator follows that ordering.
cache = build_longevity_modulation_cache( ...
    'extended_fig2b', ...
    [1, 2], ...
    {'alphaS', 'alphaH'}, ...
    [300, 250], ...
    cacheFile);
end
