function cache = generate_figS1a_data()
scriptDir = fileparts(mfilename('fullpath'));
cacheFile = fullfile(scriptDir, 'figS1a_cache.mat');

cache = build_longevity_modulation_cache( ...
    'figS1a', ...
    [5, 6], ...
    {'betaS', 'betaH'}, ...
    [300, 300], ...
    cacheFile);
end
