function data = build_fig3f_data(cfg)
if nargin < 1
    cfg = struct();
end
flexmod.ensure_paths();
cfg = flexmod.merge_config(default_config(), cfg);

startPoint = run_modulation_task(struct( ...
    'modelType', 'temperature', ...
    'startParams', cfg.temperature.initialParams, ...
    'goalOrder', {{'period', 'amplitude'}}, ...
    'goals', struct('period', cfg.fig3f.startTarget(1), 'amplitude', cfg.fig3f.startTarget(2)), ...
    'controlledParams', {{'ET', 'Temperature'}}, ...
    'fmam', struct('dlambdaCap', 1)));

directPath = run_modulation_task(struct( ...
    'modelType', 'temperature', ...
    'initialSolverView', startPoint.solverView, ...
    'initialDerivedView', startPoint.derivedView, ...
    'goalOrder', {{'period', 'amplitude'}}, ...
    'goals', struct('period', cfg.fig3f.endTarget(1), 'amplitude', cfg.fig3f.endTarget(2)), ...
    'controlledParams', {{'ET', 'Temperature'}}, ...
    'fmam', struct('dlambdaCap', cfg.fmam.dlambdaCap)));

directMid = run_modulation_task(struct( ...
    'modelType', 'temperature', ...
    'initialSolverView', startPoint.solverView, ...
    'initialDerivedView', startPoint.derivedView, ...
    'goalOrder', {{'period', 'amplitude'}}, ...
    'goals', struct('period', cfg.fig3f.directMidTarget(1), 'amplitude', cfg.fig3f.directMidTarget(2)), ...
    'controlledParams', {{'ET', 'Temperature'}}, ...
    'fmam', struct('dlambdaCap', 1)));

orthPeriod = run_modulation_task(struct( ...
    'modelType', 'temperature', ...
    'initialSolverView', startPoint.solverView, ...
    'initialDerivedView', startPoint.derivedView, ...
    'goalOrder', {{'period', 'amplitude'}}, ...
    'goals', struct('period', cfg.fig3f.orthMidTarget(1), 'amplitude', cfg.fig3f.orthMidTarget(2)), ...
    'controlledParams', {{'ET', 'Temperature'}}, ...
    'fmam', struct('dlambdaCap', cfg.fmam.dlambdaCap)));

orthAmplitude = run_modulation_task(struct( ...
    'modelType', 'temperature', ...
    'initialSolverView', orthPeriod.solverView, ...
    'initialDerivedView', orthPeriod.derivedView, ...
    'goalOrder', {{'period', 'amplitude'}}, ...
    'goals', struct('period', cfg.fig3f.endTarget(1), 'amplitude', cfg.fig3f.endTarget(2)), ...
    'controlledParams', {{'ET', 'Temperature'}}, ...
    'fmam', struct('dlambdaCap', cfg.fmam.dlambdaCap)));

startPoint.orbit = flexmod.shift_cycle_to_max(startPoint.orbit);
directMid.orbit = flexmod.shift_cycle_to_max(directMid.orbit);
directPath.orbit = flexmod.shift_cycle_to_max(directPath.orbit);
orthPeriod.orbit = flexmod.shift_cycle_to_max(orthPeriod.orbit);
orthAmplitude.orbit = flexmod.shift_cycle_to_max(orthAmplitude.orbit);

data = struct();
data.startPoint = startPoint;
data.directPath = directPath;
data.directMid = directMid;
data.orthPeriod = orthPeriod;
data.orthAmplitude = orthAmplitude;
end
