function cfg = default_config()
%DEFAULT_CONFIG Default MATCONT-specific configuration for orbitmatcont.
%
% This package keeps only the incremental settings needed by the MATCONT
% backend here. Scenario-specific scripts are expected to override the
% relevant fields for each concrete task.

cfg = struct( ...
    'solver_name', 'ode45', ...
    'solver_tol', struct('RelTol', 1e-7, 'AbsTol', 1e-9), ...
    'transientFraction', 0.5, ...
    'extractNumPoints', 400, ...
    'matcont_root', default_matcont_root(), ...
    'matcont_odefile', [], ...
    'matcont_active_parameter', [], ...
    'matcont_parameter_values', [], ...
    'matcont_ntst', 20, ...
    'matcont_ncol', 4, ...
    'matcont_tolerance', 1e-2, ...
    'matcont_window_timespan', [], ...
    'matcont_cycle_window_factor', 1.25, ...
    'matcont_options', struct('Adapt', 5), ...
    'matcont_parameter_tolerance', 1e-6, ...
    'matcont_return_max_points', 1000, ...
    'matcont_return_scan_both_directions', true);
end

function root = default_matcont_root()
packageDir = fileparts(mfilename('fullpath'));
root = fullfile(fileparts(packageDir), 'MatCont7p6');
end
