function orbit = find_orbit(model, params, cfg, initialState)
flexmod.ensure_paths();

if nargin < 4 || isempty(initialState)
    initialState = cfg.initialState;
end

params = reshape(params, 1, []);
y0 = initialState(:);
singleWindow = cfg.orbit.searchWindow;
maxWindows = max(1, numel(cfg.orbit.windowGrowth));
poResult = extract_periodic_orbit(@odefun, y0, params, build_po_options(cfg, singleWindow, maxWindows));

if poResult.has_orbit
    orbit = finalize_orbit(poResult);
    return
end

orbit = struct( ...
    'success', false, ...
    'message', poResult.message, ...
    't', zeros(0, 1), ...
    'y', zeros(0, numel(y0)), ...
    'period', NaN, ...
    'amplitude', NaN, ...
    'yMax', NaN, ...
    'yMin', NaN, ...
    'proteinIndex', 2, ...
    'result', poResult);

    function dydt = odefun(~, y, parameter)
        dydt = model.rhs(y, parameter);
    end
end

function opts = build_po_options(cfg, singleWindow, maxWindows)
opts = struct( ...
    'solver_name', 'ode45', ...
    'single_timespan', singleWindow, ...
    'max_windows', maxWindows, ...
    'event', 1, ...
    'solver_tol', cfg.orbit.solverTol, ...
    'minCrossings', cfg.orbit.minCrossings, ...
    'transientFraction', cfg.orbit.transientFraction, ...
    'samplesPerCycle', cfg.orbit.samplesPerCycle, ...
    'extractNumPoints', cfg.orbit.extractNumPoints);
end

function orbit = finalize_orbit(poResult)
protein = poResult.orbit_y(:, 2);
orbit = struct( ...
    'success', true, ...
    'message', poResult.message, ...
    't', poResult.orbit_t(:), ...
    'y', poResult.orbit_y, ...
    'period', poResult.period, ...
    'amplitude', 0.5 * (max(protein) - min(protein)), ...
    'yMax', max(protein), ...
    'yMin', min(protein), ...
    'proteinIndex', 2, ...
    'result', poResult);
end
