function orbit = orbit_from_state(stateLike, params)
params = reshape(params, 1, []);
t = stateLike.t(:);
y = stateLike.TS_var;
period = stateLike.period;

if isempty(t) || isempty(y) || ~(isfinite(period) && period > 0)
    error('flexmod:InvalidStateOrbit', ...
        'Cannot reconstruct orbit from state because the time series or period is invalid.');
end

if abs(t(end) - period) > eps(max(period, 1))
    t = [t; period];
    y = [y; y(1, :)];
end

proteinIndex = min(2, size(y, 2));
protein = y(:, proteinIndex);

orbit = struct( ...
    'success', true, ...
    'message', 'Reconstructed directly from FMAM state.', ...
    't', t, ...
    'y', y, ...
    'period', period, ...
    'amplitude', 0.5 * (max(protein) - min(protein)), ...
    'yMax', max(protein), ...
    'yMin', min(protein), ...
    'proteinIndex', proteinIndex, ...
    'params', params, ...
    'result', struct('source', 'state'));
end
