function orbit = refine_orbit_from_state(model, params, cfg, stateLike)
flexmod.ensure_paths();

params = reshape(params, 1, []);
period = stateLike.period;
series = stateLike.TS_var;

if isempty(series) || ~(isfinite(period) && period > 0)
    orbit = flexmod.find_orbit(model, params, cfg, cfg.initialState);
    return
end

nSamples = size(series, 1);
phaseFraction = cfg.orbit.stateInitPhaseFraction;
sampleIndex = 1 + floor(phaseFraction * max(nSamples - 1, 0));
sampleIndex = min(max(sampleIndex, 1), nSamples);
y0 = series(sampleIndex, :).';

refinePeriods = max(1, cfg.orbit.refinePeriods);
transientPeriods = min(max(0, cfg.orbit.refineTransientPeriods), refinePeriods);
poOpts = struct( ...
    'solver_name', 'ode45', ...
    'tspan', [0, refinePeriods * period], ...
    'event', 1, ...
    'solver_tol', cfg.orbit.solverTol, ...
    'minCrossings', cfg.orbit.minCrossings, ...
    'transientTime', transientPeriods * period, ...
    'samplesPerCycle', cfg.orbit.samplesPerCycle, ...
    'extractNumPoints', cfg.orbit.extractNumPoints);
poResult = extract_periodic_orbit(@odefun, y0, params, poOpts);

if poResult.has_orbit
    orbit = finalize_orbit(poResult);
    return
end

orbit = flexmod.find_orbit(model, params, cfg, y0);

    function dydt = odefun(~, y, parameter)
        dydt = model.rhs(y, parameter);
    end
end

function orbit = finalize_orbit(poResult)
proteinIndex = min(2, size(poResult.orbit_y, 2));
protein = poResult.orbit_y(:, proteinIndex);
orbit = struct( ...
    'success', true, ...
    'message', poResult.message, ...
    't', poResult.orbit_t(:), ...
    'y', poResult.orbit_y, ...
    'period', poResult.period, ...
    'amplitude', 0.5 * (max(protein) - min(protein)), ...
    'yMax', max(protein), ...
    'yMin', min(protein), ...
    'proteinIndex', proteinIndex, ...
    'result', poResult);
end
